version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../grocy:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ../grocy:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge